application: webrtcdevelop
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /
  static_files: www/app.html
  upload: www/app.html

- url: /
  static_dir: www

libraries:
- name: webapp2
  version: "2.5.2"
